" Vimscript Setup: {{{1
let s:save_cpo = &cpo
set cpo&vim


let s:emotes = [
      \ {'emote': '( ͡° ͜ʖ ͡°)', 'tags': ['lenny', ]},
      \ {'emote': 'ʘ‿ʘ', 'tags': ['approval', ]},
      \ {'emote': '(╯°□°）╯︵ ┻━┻', 'tags': ['table', ]},
      \ {'emote': 'ಥ_ಥ', 'tags': []},
      \ {'emote': '¯\_(ツ)_/¯', 'tags': []},
      \ {'emote': '༼ つ ◕_◕ ༽つ', 'tags': []},
      \ {'emote': '(☞ﾟヮﾟ)☞', 'tags': []},
      \ {'emote': '▄︻̷̿┻̿═━一', 'tags': []},
      \ {'emote': '(ง'̀-'́)ง', 'tags': ['donger', ]},
      \ {'emote': 'ಠ_ಠ', 'tags': []},
      \ {'emote': 'ლ(ಠ益ಠლ)', 'tags': ['donger', ]},
      \ {'emote': 'ᕙ(⇀‸↼‶)ᕗ', 'tags': ['donger', ]},
      \ {'emote': '(ง ͠° ͟ل͜ ͡°)ง', 'tags': ['lenny', 'donger', ]},
      \ {'emote': '(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)', 'tags': []},
      \ {'emote': '｡◕‿◕｡', 'tags': ['approval', ]},
      \ {'emote': '( ͡ᵔ ͜ʖ ͡ᵔ )', 'tags': ['lenny', ]},
      \ {'emote': 'ლ,ᔑ•ﺪ͟͠•ᔐ.ლ', 'tags': ['donger', ]},
      \ {'emote': 'ᕦ(ò_óˇ)ᕤ', 'tags': ['donger', ]},
      \ {'emote': 'Q(Ò_ÓQ)', 'tags': ['donger', ]},
      \ {'emote': '༼ ºل͟º ༽', 'tags': []},
      \ {'emote': 'ヽ༼ຈل͜ຈ༽ﾉ', 'tags': []},
      \ {'emote': 'ヽ(´ー｀)ノ', 'tags': []},
      \ {'emote': 'ʕ•ᴥ•ʔ', 'tags': ['approval', ]},
      \ {'emote': 'ヽ(´▽`)/', 'tags': ['approval', ]},
      \ {'emote': '（　ﾟДﾟ）', 'tags': []},
      \ {'emote': '☜(⌒▽⌒)☞', 'tags': ['approval', ]},
      \ {'emote': '¯\_(⊙︿⊙)_/¯', 'tags': []},
      \ {'emote': 'Ƹ̵̡Ӝ̵̨̄Ʒ', 'tags': []},
      \ {'emote': '(`･ω･´)', 'tags': []},
      \ {'emote': 'ლ(=ↀωↀ=)ლ', 'tags': []},
      \ {'emote': 'ヾ(*ΦωΦ)ﾉ', 'tags': []},
      \ {'emote': '(=^-ω-^=)', 'tags': ['approval', ]},
      \ {'emote': '( =①ω①=)', 'tags': []},
      \ {'emote': '（。ˇ ⊖ˇ）♡', 'tags': []},
      \ {'emote': 'ლ(´◉❥◉｀ლ)', 'tags': []},
      \ {'emote': '(˘▼˘>ԅ( ˘⌣ƪ)', 'tags': ['approval', ]},
      \ {'emote': '(⊙︿⊙✿)', 'tags': []},
      \ {'emote': '(இ﹏இ`｡)', 'tags': []},
      \ {'emote': '༼ ༎ຶ ෴ ༎ຶ༽', 'tags': []},
      \ {'emote': '(ఠ్ఠ ˓̭ ఠ్ఠ)', 'tags': []},
      \ {'emote': '(●__●)', 'tags': []},
      \ {'emote': 'ਉ_ਉ', 'tags': []},
      \ {'emote': '(╥╯θ╰╥)', 'tags': []},
      \ {'emote': '｡ﾟ(ﾟ∩´﹏`∩ﾟ)ﾟ｡', 'tags': []},
      \ {'emote': '˞̣̣̣̀ ᶿ᷄ ˈ̯̥̮ ᶿ᷅', 'tags': []},
      \ {'emote': '(〃￣ω￣〃ゞ', 'tags': []},
      \ {'emote': '(╯_╰)', 'tags': []},
      \ {'emote': '(•⊙ω⊙•)', 'tags': []},
      \ {'emote': '(≧◡≦)', 'tags': []},
      \ {'emote': '／(x~x)＼', 'tags': []},
      \ {'emote': 'o(╥﹏╥)o', 'tags': []},
      \ {'emote': '⁽⁽ƈ ͡ (ु ˲̥̥̥́ ˱̥̥̥̀) ु⁾⁾', 'tags': []},
      \ {'emote': 'ㅇㅅㅇ', 'tags': []},
      \ {'emote': '٩(͡๏̯͡๏)۶', 'tags': []},
      \ {'emote': '(๏̯͡๏)', 'tags': []},
      \ {'emote': '(　-̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥᷄◞ω◟-̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥̥᷅ )', 'tags': []},
      \ {'emote': '(•ิ_•ิ)?', 'tags': []},
      \ {'emote': '`(๑ △ ๑)`*', 'tags': []},
      \ {'emote': '（￣へ￣）', 'tags': []},
      \ {'emote': '(￣ェ￣;)', 'tags': []},
      \ {'emote': '（￣～￣;）', 'tags': []},
      \ {'emote': '<(￣︶￣)>', 'tags': []},
      \ {'emote': '[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]', 'tags': []},
      \ {'emote': 'ヽ༼ ಠ益ಠ ༽ﾉ', 'tags': []},
      \ {'emote': '༼✷ɷ✷༽', 'tags': []},
      \ {'emote': '(✖╭╮✖)', 'tags': []},
      \ {'emote': '(≖͞_≖̥)', 'tags': []},
      \ {'emote': '≖‿≖', 'tags': []},
      \ {'emote': '（Ω_Ω）', 'tags': []},
      \ {'emote': '┗( ●-﹏ ｀｡)づ', 'tags': []},
      \ {'emote': 'ヾ(￣□￣;)ﾉ', 'tags': []},
      \ {'emote': '*｡٩(ˊωˋ*)و✧*｡', 'tags': []},
      \ {'emote': 't ( - _ - t )', 'tags': []},
      \ {'emote': '₍₍ ᕕ( ･᷄ὢ･᷅ )ᕗ⁾⁾', 'tags': []},
      \ {'emote': '☆', 'tags': []},
      \ {'emote': '╭( ･ㅂ･)و ̑̑', 'tags': []},
      \ {'emote': '(－‸ლ)', 'tags': []},
      \ {'emote': '✿', 'tags': []},
      \ {'emote': '♥‿♥', 'tags': []},
      \ {'emote': '(ﾉ> ◇ <)ﾉ', 'tags': []},
      \ {'emote': '♬♪♫♩', 'tags': []},
      \ {'emote': '(⊙ヮ⊙)', 'tags': []},
      \ {'emote': '(づ￣ ³￣)づ', 'tags': []},
      \ {'emote': 'o(≧∇≦o)', 'tags': []},
      \ {'emote': '≧(´▽｀)≦', 'tags': []},
      \ {'emote': '(͠≖ ͜ʖ͠≖)', 'tags': []},
      \ {'emote': '¿ⓧ_ⓧﮌ', 'tags': []},
      \ {'emote': '╭∩╮( ͡⚆ ͜ʖ ͡⚆)╭∩╮', 'tags': []},
      \ {'emote': '┌∩┐(◣_◢)┌∩┐', 'tags': []},
      \ {'emote': '( ° ͜ʖ͡°)╭∩╮', 'tags': []},
      \ {'emote': 'щ（ﾟДﾟщ）', 'tags': []},
      \ {'emote': '⊂(◉‿◉)つ', 'tags': []},
      \ {'emote': '°‿‿°', 'tags': []},
      \ {'emote': '⊙▃⊙', 'tags': []},
      \ {'emote': 'q(❂‿❂)p', 'tags': []},
      \ {'emote': 'ヾ(⌐■_■)ノ', 'tags': []},
      \ {'emote': '-[ºل͟º]-', 'tags': []},
      \ {'emote': '♪ᕕ(ᐛ)ᕗ', 'tags': []},
      \ {'emote': '( ¬‿¬)', 'tags': []},
      \ {'emote': '┗(＾0＾)┓', 'tags': []},
      \ {'emote': 'ლ(╹◡╹ლ)', 'tags': []},
      \ {'emote': 'Ѱζ༼ᴼل͜ᴼ༽ᶘѰ', 'tags': []},
      \ {'emote': '༼ ºل͟º༼ ºل͟º༼ ºل͟º༼ ºل͟º ༽ºل͟º ༽ºل͟º ༽ºل͟º ༽', 'tags': []},
      \ {'emote': '༼ つ ಥ_ಥ ༽つ', 'tags': []},
      \ {'emote': 'ヽ༼ຈ┏ل͜┓ຈ༽ﾉ', 'tags': []},
      \ {'emote': '༼ ಠل͟ರೃ ༽', 'tags': []},
      \ {'emote': 'ᕙ(˵ ಠ ਊ ಠ ˵)ᕗ', 'tags': []},
      \ {'emote': '/╲/\╭( ͡° ͡° ͜ʖ ͡° ͡°)╮/\╱\', 'tags': []},
      \ {'emote': 'ヽ( ͝° ͜ʖ͡°)ﾉ', 'tags': []},
      \ {'emote': '/╲/\╭(ఠ్ఠఠ్ఠ˓̭ ఠ్ఠఠ్ఠ)╮/\╱\', 'tags': []},
      \ {'emote': '\(༎ຶ益༎ຶ)ᕗ', 'tags': []},
      \ {'emote': 'ᕦ༼༎ຶ_༎ຶ༽ᕗ', 'tags': []},
      \ {'emote': '(๑˃̵ᴗ˂̵)و', 'tags': []},
      \ {'emote': '┐('～`；)┌', 'tags': []},
      \ {'emote': 'ლ(´ڡ`ლ)', 'tags': []},
      \ {'emote': '【°〜°】', 'tags': []},
      \ {'emote': '¯\\\_(ツ)_/¯', 'tags': []},
      \ {'emote': '(ಥ﹏ಥ)', 'tags': []},
      \ {'emote': '┬──┬ ノ( ゜-゜ノ)', 'tags': ['table', ]},
      \ {'emote': 'ノ┬─┬ノ ︵ ( \o°o)\', 'tags': ['table', ]},
      \ {'emote': '┬─┬ノ( º \_ ºノ)', 'tags': ['table', ]},
      \ {'emote': 'ᶘ ᵒᴥᵒᶅ', 'tags': []},
      \ {'emote': '(ﾟ∀ﾟ)☞', 'tags': []},
      \ {'emote': '(づ°‿°.)づ', 'tags': []},
      \ {'emote': '(V) (°,,,°) (V)', 'tags': []},
      \ {'emote': '༼( ͠° ͟ʖ ͡°)༽', 'tags': []},
      \ {'emote': 'ヽ༼ಢ_ಢ༽ﾉ☂', 'tags': []},
]

function! s:local_function()
  echom "change s:local_function"
endfunction

function! emotes#some_function()
  echo "Hello world!"
endfunction

" Teardown:{{{1
let &cpo = s:save_cpo

" Misc: {{{1
" vim: set ft=vim ts=2 sw=2 tw=78 et fdm=marker:
